name: Run Tests
on:
  push:
    branches: [ main ]

jobs:
  test-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore dotnet-app/ProjectFile.csproj
          dotnet restore dotnet-app.Tests/ProjectFile-Tests.csproj

      - name: Run .NET tests (generate TRX)
        run: |
          dotnet test dotnet-app.Tests/ProjectFile-Tests.csproj --logger "console;verbosity=detailed" --logger "trx;LogFileName=TestResults.trx" --results-directory dotnet-app.Tests/TestResults

      - name: Upload .NET Test Report
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-report
          path: dotnet-app.Tests/TestResults

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python Tests and Generate XML Report
        run: |
          cd python-app
          pip install --upgrade pip
          pip install unittest-xml-reporting
          python test_math_utils.py

      - name: Upload Python Test Report
        uses: actions/upload-artifact@v4
        with:
          name: python-test-report
          path: python-app/test-reports
